-- 코드를 입력하세요
SELECT 
    A.AUTHOR_ID, 
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(SALES * PRICE)
FROM 
    BOOK B,
    AUTHOR A,
    BOOK_SALES BS
WHERE 
    B.BOOK_ID = BS.BOOK_ID and
    A.AUTHOR_ID	 = B.AUTHOR_ID	and
    date_format(SALES_DATE,'%Y-%m') ='2022-01'
GROUP BY AUTHOR_ID,CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC