-- 코드를 입력하세요
SELECT * FROM
(SELECT date_format(SALES_DATE,'%Y-%m-%d') as SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE 
WHERE date_format(SALES_DATE,'%Y-%m')='2022-03'
UNION 
SELECT date_format(SALES_DATE,'%Y-%m-%d') as SALES_DATE, PRODUCT_ID, NULL as USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE 
WHERE date_format(SALES_DATE,'%Y-%m')='2022-03'
) as SALES

ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC
