-- 코드를 작성해주세요
WITH SIZE_RANK AS (
    SELECT 
        *,
        RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS RANKING
    FROM ECOLI_DATA
)

SELECT 
    ID,
    CASE
        WHEN ((RANKING) / CNT) * 100 <= 25 THEN 'CRITICAL'
        WHEN ((RANKING) / CNT) * 100 <= 50 THEN 'HIGH'
        WHEN ((RANKING) / CNT) * 100 <= 75 THEN 'MEDIUM'
        WHEN ((RANKING) / CNT) * 100 <= 100 THEN 'LOW'
    END AS COLONY_NAME
FROM SIZE_RANK SR,
     (SELECT COUNT(*) AS CNT FROM ECOLI_DATA) CNT
ORDER BY ID
