-- 코드를 입력하세요
WITH R AS (
    SELECT
        *
    FROM REST_INFO
    WHERE 
        ADDRESS LIKE "서울시%" OR
        ADDRESS LIKE "서울특별시%" OR
        TEL LIKE "02-%"
)

SELECT 
    R.REST_ID,
    REST_NAME,
    FOOD_TYPE,
    FAVORITES,
    ADDRESS,
    ROUND(AVG(IFNULL(REVIEW_SCORE,0)),2) AS SCORE
FROM R
     JOIN REST_REVIEW AS RV
     USING(REST_ID)
GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC