-- 코드를 입력하세요
WITH 2021_USER AS (
    SELECT 
        *
    FROM 
        USER_INFO
    WHERE 
        YEAR(JOINED) = 2021
)

SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT OS.USER_ID) AS PUCHASED_USERS,
    ROUND(COUNT(DISTINCT OS.USER_ID)/TOTAL_CNT,1) AS PUCHASED_RATIO
FROM
    ONLINE_SALE AS OS
    JOIN
    2021_USER AS UI
    USING(USER_ID),
    (SELECT COUNT(*) AS TOTAL_CNT FROM 2021_USER) AS TC
GROUP BY
    YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY
    YEAR ASC, 
    MONTH ASC