-- 코드를 작성해주세요
WITH QUARTER_ECOLI AS (
    SELECT
    *,
    DATE_FORMAT(DIFFERENTIATION_DATE, "%m"),
    CASE
        WHEN DATE_FORMAT(DIFFERENTIATION_DATE, "%m") <= 3 THEN '1Q'
        WHEN DATE_FORMAT(DIFFERENTIATION_DATE, "%m") <= 6 THEN '2Q'
        WHEN DATE_FORMAT(DIFFERENTIATION_DATE, "%m") <= 9 THEN '3Q'
        WHEN DATE_FORMAT(DIFFERENTIATION_DATE, "%m") <= 12 THEN '4Q'
    END AS QUARTER
FROM
    ECOLI_DATA
)

SELECT 
    QUARTER,
    COUNT(ID) AS ECOLI_COUNT
FROM 
    QUARTER_ECOLI
GROUP BY 
    QUARTER
ORDER BY QUARTER ASC
