-- 코드를 입력하세요
SELECT 
    PRODUCT_ID,
    PRODUCT_NAME,
    SUM(AMOUNT*PRICE) AS TOTAL_SALES
FROM FOOD_ORDER
     JOIN
     FOOD_PRODUCT
     USING(PRODUCT_ID)
WHERE
    DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY
    PRODUCT_ID,
    PRODUCT_NAME
ORDER BY
    TOTAL_SALES DESC, PRODUCT_ID ASC