-- 코드를 입력하세요
WITH RENTAL_PERIOD AS (
    SELECT 
        CH.*,
        CASE
            WHEN DATEDIFF(CH.END_DATE, CH.START_DATE)<7 THEN null
            WHEN DATEDIFF(CH.END_DATE, CH.START_DATE)<30 THEN '7일 이상'
            WHEN DATEDIFF(CH.END_DATE, CH.START_DATE)<90 THEN '30일 이상'
            ELSE '90일 이상'
        END AS DURATION_TYPE
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
), CAR_RENTAL AS (
    SELECT 
        *
    FROM 
        RENTAL_PERIOD RP
        JOIN
        CAR_RENTAL_COMPANY_CAR CR
        USING(CAR_ID)
    WHERE
        CR.CAR_TYPE = '트럭'
)   

SELECT 
    HISTORY_ID,
    CASE 
        WHEN DISCOUNT_RATE is null 
            THEN DAILY_FEE * (DATEDIFF(CR.END_DATE, CR.START_DATE) + 1)
        ELSE
            FLOOR(DAILY_FEE * (DATEDIFF(CR.END_DATE, CR.START_DATE) + 1) * (100 - DISCOUNT_RATE) / 100) 
    END AS FEE
FROM 
    CAR_RENTAL CR
    LEFT OUTER JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
    USING(DURATION_TYPE,CAR_TYPE)
ORDER BY
    FEE DESC,
    HISTORY_ID DESC

