WITH DURATION_TABLE AS (
    SELECT 
        HISTORY_ID,
        C.*,
        DATEDIFF(END_DATE, START_DATE) + 1 AS RENT_DATE,
        CASE 
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7  THEN '7일 이상'
            ELSE 
                ''
        END AS DURATION_TYPE
    FROM 
        CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        JOIN
        CAR_RENTAL_COMPANY_CAR C
        USING(CAR_ID)
    WHERE
        CAR_TYPE='트럭'
)

SELECT 
    HISTORY_ID,
    ROUND(RENT_DATE * DAILY_FEE * (100 - IFNULL(DISCOUNT_RATE,0)) / 100) AS FEE
FROM 
    DURATION_TABLE D
    LEFT JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON D.CAR_TYPE = P.CAR_TYPE AND D.DURATION_TYPE = P.DURATION_TYPE
ORDER BY
    FEE DESC,
    HISTORY_ID DESC