-- 코드를 작성해주세요
WITH MAX_SIZE_BY_YEAR AS (
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS DATE,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM 
        ECOLI_DATA
    GROUP BY
        YEAR(DIFFERENTIATION_DATE)
)

SELECT
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    MAX_SIZE - SIZE_OF_COLONY AS YEAR_DEV,
    ID
FROM 
    ECOLI_DATA AS E
    LEFT JOIN
    MAX_SIZE_BY_YEAR AS MS
    ON YEAR(DIFFERENTIATION_DATE) = MS.DATE
ORDER BY
    YEAR ASC,
    YEAR_DEV ASC
    
