-- 코드를 입력하세요
SELECT
    DISTINCT CR.CAR_ID
    
FROM 
    CAR_RENTAL_COMPANY_CAR CR
    LEFT JOIN
    CAR_RENTAL_COMPANY_RENTAL_HISTORY CRH
    USING(CAR_ID)
WHERE
    CAR_TYPE = '세단' AND
    DATE_FORMAT(START_DATE, "%m") = 10
ORDER BY
    CAR_ID DESC